run:
  timeout: 5m

linters:
  disable-all: false
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  staticcheck:
    checks:
      - all
      - "-SA4010"  # Disable SA4010 check
